image : rvancea/maven-chrome-jdk8:latest
stages:
        -build
        -test
build-backend : 
        stage : build 
        script : 
                - mvn clean install
        only:
                -master
               `-staging 
test-backend :
        stage : test 
        script : 
                - mvn clean verify
